describe("Busted unit testing framework", function()
  describe("should be awesome", function()
    it("should have mocks and spies for functional tests", function()
      -- local test_helper = require("kong.plugins.jwt-keycloak.keycloak_keys")
      -- local keycloak_keys = require("kong.plugins.jwt-keycloak.keycloak_keys")
      -- keycloak_keys.get_issuer_keys("http://localhost:8080/auth/realms/master")
      -- spy.on(thing, "greet")
      -- thing.greet("Hi!")

      -- assert.spy(thing.greet).was.called()
      -- assert.spy(thing.greet).was.called_with("Hi!")
    end)
  end)
end)